
image:
  registry: ""
  repository: ""
  tag: ""

clickhouse:
  shards: 1
  replicaCount: 1 
  keeper: 
    enabled: false
  auth: 
    username: "default"
    password: "insertpassword" 
  zookeeper: 
    enabled: false
