apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - args:
            - uvicorn
            - chromadb.app:app
            - --workers
            - "1"
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          env:
            - name: CHROMA_DB_IMPL
              value: clickhouse
            - name: CLICKHOUSE_HOST
              value: clickhouse
            - name: CLICKHOUSE_PORT
              value: "8123"
          image: ghcr.io/chroma-core/chroma:0.3.11
          name: server
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /index_data
              name: index-data
      restartPolicy: Always
      volumes:
        - name: index-data
          persistentVolumeClaim:
            claimName: index-data
